services:
  # NGINX
  nginx:
    restart: always
    container_name: nginx_proxy
    build:
      context: ./NGINX
      dockerfile: Dockerfile_NGINX
    ports:
      - "8080:80"
    volumes:
      - ./NGINX/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./NGINX/web:/usr/share/nginx/html:ro
    networks:
      - smart_cities_network
    depends_on:
      - flask_api
  
  # Python API
  flask_api:
    restart: always
    container_name: flask_api
    build:
      context: ./Flask_API
      dockerfile: Dockerfile_Flask
    expose:
      - "5000"
    volumes:
      - ./Flask_API/app:/app
    environment:
      - DATABASE_HOST=${PG_HOST}
      - DATABASE_USER=${PG_USER}
      - DATABASE_PASSWORD=${PG_PASSWORD}
      - DATABASE_NAME=${PG_DB_NAME}
    depends_on:
      - postgres_db
    networks:
      - smart_cities_network
  
  # PostgreSQL
  postgres_db:
    restart: always
    image: postgres:15
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    # ports:
    #   - "5432:5432"
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB_NAME}
    networks:
      - smart_cities_network

networks:
  smart_cities_network:
    driver: bridge

volumes:
  postgres_data: