services:
  # NGINX
  nginx:
    restart: always
    container_name: nginx_proxy
    build:
      context: ./NGINX
      dockerfile: Dockerfile_NGINX
    ports:
      - "8080:8080"
    volumes:
      - ./NGINX/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./NGINX/web:/usr/share/nginx/html:ro
    networks:
      - smart_cities_network
    depends_on:
      - grafana
  
  # Python API
  flask_api:
    restart: always
    container_name: flask_api
    build:
      context: ./Flask_API
      dockerfile: Dockerfile_Flask
    expose:
      - "5000"
    volumes:
      - ./Flask_API/app:/app
    environment:
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DB_NAME=${PG_DB_NAME}
    depends_on:
      - postgres_db
    networks:
      - smart_cities_network
  
  # PostgreSQL
  postgres_db:
    restart: always
    image: postgres:15
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB_NAME}
    networks:
      - smart_cities_network

  # GRAFANA
  grafana:
    image: grafana/grafana-oss:11.1.4
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    # expose:
    #   - "3000"
    environment:
      - TZ=America/Guayaquil
      - GF_SERVER_ROOT_URL=http://localhost:3000/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./grafana-storage:/var/lib/grafana/
    depends_on:
      - postgres_db
    networks:
      - smart_cities_network
  
  # ngrok tunnel agent 
  ngrok_agent:
    container_name: ngrok_agent
    restart: always
    image: ngrok/ngrok:3
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    depends_on:
      - flask_api
    command: http --url=${NGROK_URL} flask_api:5000
    networks:
      - smart_cities_network

networks:
  smart_cities_network:
    driver: bridge

volumes:
  postgres_data: