# Dockerfile
FROM python:3.10-slim

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos necesarios al contenedor
COPY app app

# Instala las dependencias
RUN pip install --no-cache-dir -r app/requirements.txt

# Expone el puerto donde Gunicorn servirá la API
EXPOSE 5000

# Comando para ejecutar la aplicación usando Gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]
